# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "backend"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "khana-backend"
s3_prefix = "khana-backend"
region = "ap-south-1"
disable_rollback = true
parameter_overrides = "DBHOST=\"khanadatabase.czwecio2ew2d.ap-south-1.rds.amazonaws.com\" DBNAME=\"khana_test\" DBUSER=\"khanadb\" DBPASSWORD=\"TechKhana#24\" DBPORT=\"3306\" SMSKEY=\"e2b658cd81f940afa781b043878a21da\" SMSHEADER=\"ea2a110e707044d7875e536624e75a95\" SMSURL=\"http://sms.pearlsms.com/public/sms/sendjson\""
#parameter_overrides = "DBHOST=\"ka-devops.crqw00kkqjni.ap-south-1.rds.amazonaws.com\" DBNAME=\"khana_prod\" DBUSER=\"kaprod\" DBPASSWORD=\"Khana2020\" DBPORT=\"3306\" SMSKEY=\"e2b658cd81f940afa781b043878a21da\" SMSHEADER=\"ea2a110e707044d7875e536624e75a95\" SMSURL=\"http://sms.pearlsms.com/public/sms/sendjson\""
image_repositories = []

[default.package.parameters]
resolve_s3 = false

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
