AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Node.js Lambda with API Gateway

Globals:
  Function:
    Timeout: 10

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  DevLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-custom-api-dev
      Handler: server.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /custom-api
            Method: GET

  ProdLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-custom-api-prod
      Handler: server.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /custom-api
            Method: GET
