name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install Tree (for debugging)
        run: sudo apt-get install -y tree

      - name: Setup Common Layer Structure
        run: |
          # Create the directory structure
          mkdir -p src/layers/common-layer/nodejs/node_modules/common-layer

          # Create package.json if it doesn't exist
          if [ ! -f src/layers/common-layer/nodejs/node_modules/common-layer/package.json ]; then
            echo '{
              "name": "common-layer",
              "version": "1.0.0",
              "description": "Common code shared across lambda functions",
              "main": "index.js",
              "dependencies": {}
            }' > src/layers/common-layer/nodejs/node_modules/common-layer/package.json
          fi

      - name: Setup Makefile
        run: |
          # Create the Makefile with proper content
          echo '.PHONY: build-CommonLayer

          build-CommonLayer:
          	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
          	cp -r src/layers/common-layer/nodejs/node_modules/common-layer/* "$(ARTIFACTS_DIR)/nodejs/"' > src/layers/common-layer/Makefile

          # Convert CRLF to LF
          sed -i 's/\r$//' src/layers/common-layer/Makefile

          # Fix permissions
          chmod +x src/layers/common-layer/Makefile

      - name: Verify Directory Structure
        run: |
          echo "Directory structure:"
          tree src/layers || true

          echo -e "\nMakefile content:"
          cat src/layers/common-layer/Makefile

      - name: Install Dependencies
        run: |
          # Install common layer dependencies
          cd src/layers/common-layer/nodejs/node_modules/common-layer
          npm install
          cd ../../../../../..

          # Install main project dependencies
          npm install

      - name: Build and Deploy
        env:
          SAM_CLI_TELEMETRY: 0
        run: |
          sam build --parallel
