name: Deploy to AWS

on:
  push:
    branches:
      - Node2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install # This will install node_modules

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Lambda
        run: |
          sam build
          # sam deploy --no-confirm-changeset --stack-name my-lambda-stack --resolve-s3 --capabilities CAPABILITY_IAM
          sam deploy --parameter-overrides Environment=test
